#!/bin/bash

### BEGIN INIT INFO
# Provides:          crossbar
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Starts crossbar
# Description:       starts crossbar
### END INIT INFO

gsv6ToWamp_dir=/home/pi/gsv-6ToWAMP
crossbar_init_log=/home/pi/gsv-6ToWAMP/logs/crossbar.init.log

#
# Write a polite log message with date and time
#
echo -e "\n \n About to start crossbar \n " >> ${crossbar_init_log}
case "$1" in
        start)
				#cd ${gsv6ToWamp_dir}
                /usr/bin/python3 /usr/local/bin/crossbar ${1} --cbdir ${gsv6ToWamp_dir}/.crossbar >> ${crossbar_init_log} &
        ;;
        restart)
                /usr/bin/python3 /usr/local/bin/crossbar ${1} --cbdir ${gsv6ToWamp_dir}/.crossbar >> ${crossbar_init_log} &
        ;;
        stop)
                /usr/bin/python3 /usr/local/bin/crossbar ${1} --cbdir ${gsv6ToWamp_dir}/.crossbar >> ${crossbar_init_log}
        ;;
        *)
                echo "Usage: /etc/init.d/crossbar {start|stop|restart}"
                exit 1
        ;;
esac
